export const styles = {
    openedCardContainer: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
        height: "100vh",
        background: "rgba(0, 0, 0, 0.8)",
        position: "fixed",
        top: 0,
        left: 0,
        zIndex: 9999,
    },
    openedCardLeft: {
        flex: 1,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    openedCardIcon: {
        width: "300px",
        height: "300px",
        borderRadius: "50%",
        objectFit: "cover",
    },
    openedCardRight: {
        flex: 1,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "40px",
        color: "#fff",
    },
    modalContent: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#fff",
        borderRadius: "10px",
        padding: "20px",
        position: "relative",
    },
    modalCloseButton: {
        position: "absolute",
        top: "10px",
        right: "10px",
        backgroundColor: "transparent",
        border: "none",
        cursor: "pointer",
        fontSize: "16px",
        color: "#fff",
    },
};
